version: '3.7'

services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web